### PR TITLE
chore: Update gl_rasterizer.h

### PR DESCRIPTION
**Pull request by eltociear**
minor fix

### CODE REVIEW

**Comment by Downlaofy123** [comment]
x2 the? how did they fumble that

**Comment by victrix-github** [comment]
Hi @eltociear,

Thanks for contributing, but **this repository here is just a mirror**. Please 
submit pull requests to [Suyu official repo on GitLab](https://gitlab.com/suyu-emu/suyu) instead.

**Comment by Fijxu** [comment]
WTF IS THIS PULL REQUEST

**Comment by RyzenDew** [comment]
Pull request go BRRRR

**Pull request closed without merging**
